/**
*
*  Purpose          :	Apex Class to have the constants
*
*  Created Date     :  	09/30/2022
*
*  Created By       :  	Abhinav Sharma
*
*  Revision Logs    :  	V_1.0 - Created
*
**/
public without sharing class Constants 
{
	public static final String SCHOOL_ID = 'schoolId';
    public static final String NUM_OF_CLASSES = 'numOfClasses';
    
    public static final String OBJECT_NAME_CONTACT = 'Contact';
    public static final String OBJECT_NAME_INDIVIDUAL = 'Individual';
    public static final String OBJECT_NAME_ACCOUNT = 'Account';
    public static final String OBJECT_NAME_SCHOOL = 'School__c';
    public static final String OBJECT_NAME_CLASS = 'Class__c';
    public static final String OBJECT_NAME_STUDENT = 'Student__c';
}